version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_fullstack_app_2
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://mahnoor:mahnoor123@bookstore.mcdjg.mongodb.net/?retryWrites=true&w=majority&appName=Bookstore
    volumes:
      - ./:/app  
      - /app/node_modules
      - /app/.next
    networks:
      - app-network


networks:
  app-network:
    driver: bridge